CREATE DATABASE ymarks
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE ymarks;

CREATE TABLE objects (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(128),
    address VARCHAR(128)
);